// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission3.Models;

namespace Mission3.Migrations
{
    [DbContext(typeof(MovieContext))]
    [Migration("20220127053314_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Mission3.Models.ApplicationResponse", b =>
                {
                    b.Property<string>("MovieName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieName");

                    b.ToTable("responses");

                    b.HasData(
                        new
                        {
                            MovieName = "Ferris Bueller's Day Off",
                            Category = "Comedy",
                            Director = "John Hughes",
                            Edited = false,
                            Rating = "PG-13",
                            Year = 1986
                        },
                        new
                        {
                            MovieName = "The Dark Knight",
                            Category = "Action/Adventure",
                            Director = "Christopher Nolan",
                            Edited = false,
                            Rating = "PG-13",
                            Year = 2008
                        },
                        new
                        {
                            MovieName = "Thor Ragnarok",
                            Category = "Action/Adventure",
                            Director = "Taika Waititi",
                            Edited = false,
                            Rating = "PG-13",
                            Year = 2017
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
